RagnarokResearchLab/RagLite

Config/realm-list.json, Core/RealmServer.lua, Tests/RealmServer/serves-realm-list.lua, Tests/smoke-test.lua, main.lua
Since the client can't easily perform disk I/O with the current design, might as well assume a proper framework (if simplistic).
=> Add a simple REST API to serve the realm list over HTTP

Core/WorldServer.lua, main.lua
Pave the way for future extension - it's still mostly throwaway code (untested prototype), but that'll change soon.
=> Refactor the Lua entry point

.luacheckrc, Core/World/C_ServerHealth.lua, Core/WorldServer.lua, Tests/WorldServer/C_ServerHealth.spec.lua, Tests/placeholder-test.lua, Tests/unit-test.lua
Only the API is tested; see last commit message for rationale.
=> Implement server health metrics and regular status updates (output to the console)

.luacheckrc, Core/WorldServer.lua, Tests/WorldServer/WorldServer.spec.lua, Tests/unit-test.lua
Most of the functionality is throwaway code, and the libuv timers can't easily be tested... so this will have to do (for now).
=> Add some unit tests for the Worldserver module

Core/WorldServer.lua
Hacking this in is a bit questionable, but I don't see a way of actually testing that we've adjusted the granularity (at least none that would be even close to reliable). So... let's just hope the reduced tick rate will be obvious if this ever breaks?
=> Set the global clock cycle on Windows to 1 ms

.luacheckrc, Tests/RealmServer/serves-realm-list.lua
Still not ideal, but it should at least not fail due to OSX TCP chunking any more...
=> Improve the consistency of the realm list HTTP test

Core/WebClient/package.json, Core/WebClient/tsconfig.json
It should be applied to all compilation runs, even in dev mode.
=> Move the tsc --noEmit flag to tsconfig.json

Core/WebClient/Interface/BasicTheme/Widgets/GameTooltip.css, Core/WebClient/Interface/BasicTheme/Widgets/PerformanceMetricsOverlay.css, Core/WebClient/Interface/BasicTheme/layout.css, Core/WebClient/Interface/IngameUI.tsx, Core/WebClient/Interface/Overlays/PerformanceMetricsOverlay.tsx, Core/WebClient/Interface/SharedRenderingContext.tsx, Core/WebClient/Interface/Tooltips/GameTooltip.tsx, Core/WebClient/Interface/basic-theme.css, Core/WebClient/Interface/reset.css, Core/WebClient/main.tsx
The keyboard shortcut isn't configurable and many other improvements could be made. But it's good enough for now.
=> Implement a basic FPS overlay with GameTooltip on hover

Core/RealmServer.lua, Core/WebClient.lua, Core/WebClient/Interface/BasicTheme/Widgets/NetworkStatusOverlay.css, Core/WebClient/Interface/IngameUI.tsx, Core/WebClient/Interface/Overlays/NetworkStatusOverlay.tsx, Core/WebClient/Interface/SharedNetworkingContext.tsx, Core/WebClient/Interface/WebClient.tsx, Core/WebClient/Interface/basic-theme.css, Core/WebClient/Interface/reset.css, Core/WebClient/main.tsx, Core/WebClient/package.json, Tests/RealmServer/serves-realm-list.lua
"Simple" is relative, all things considered... Just TypeScript and React things.
=> Implement a simple network status overlay

Core/WebClient/Interface/BasicTheme/layout.css, Core/WebClient/Interface/Overlays/DebugMenuOverlay.tsx, Core/WebClient/Interface/reset.css
=> Implement a simple loading screen toggle (to build upon later)

Core/NativeClient/NativeClient.lua, Core/NativeClient/Renderer.lua, Core/NativeClient/Shaders/BasicTriangleShader.wgsl, Core/NativeClient/gpu.lua, start-client.lua
Yet another experiment. I'm not happy with the browser restrictions and JavaScript in general, even if I really like BabylonJS.
This is exploring a different direction (which may require reinventing too many wheels to be practical). Time will tell if it's at all viable.
=> Implement a basic WebGPU based native client (as a potential alternative to the WebView-based one)

Core/NativeClient/Renderer.lua
Whoopsie, no test coverage for these parts...
=> Fix the swapchain API names that were broken in v0.0.7

Core/NativeClient/NativeClient.lua, Core/NativeClient/Renderer.lua, Core/NativeClient/Shaders/BasicTriangleShader.wgsl
It's upside down now because the projection was wrong. I'll fix that in a separate PR since it requires some plumbing (WIP).
=> Improve the WebGPU demo scene to more easily troubleshoot camera issues

Core/NativeClient/C_Camera.lua, Core/NativeClient/Renderer.lua, Core/NativeClient/Shaders/BasicTriangleShader.wgsl, Core/NativeClient/gpu.lua, Tests/NativeClient/C_Camera.spec.lua, Tests/unit-test.lua
No mouse control yet since I've yet to wire up the input events, but the basic plumbing is there (and tested).
=> Implement a camera API to generate the view and projection matrices

.gitignore, Tests/Tools/FileAnalyzer.spec.lua, Tests/unit-test.lua, Tools/FileAnalyzer.lua, Tools/analyze-gnd-files.lua
It's pretty similar to the JavaScript version, but simpler in its design.
=> Add a new utility to analyze GND files

Core/NativeClient/C_Cursor.lua, Core/NativeClient/NativeClient.lua, Tests/NativeClient/NativeClient.spec.lua
The detection is extremely basic and the state management is getting a little ugly, but it's not yet complicated enough for a FSM approach.
=> Implement camera resets via double-rightclick

Core/NativeClient/C_Camera.lua, Core/NativeClient/C_Cursor.lua, Core/NativeClient/NativeClient.lua, Tests/NativeClient/NativeClient.spec.lua
No interpolation or anything, just a very basic version to help inspect the geometry a bit more easily.
=> Implement camera zoom controls via scroll events

Core/NativeClient/C_Camera.lua, Core/NativeClient/NativeClient.lua, Tests/NativeClient/NativeClient.spec.lua
Not sure if the angles are really correct. Time will tell, presumably?
=> Implement vertical camera adjustments via scroll events

README.md
Since it's looking like WebViews are out and WebGPU is in, might as well reflect this in the documentation.
=> Update the README with more infos about the WebGPU-based client

Tools/export-ebm-as-bmp.lua
Trivial, but it might still come in handy at some point...
=> Add a script to export EBM files as BMP

Core/FileFormats/RagnarokGND.lua
Benchmarks suggest there's no discernible performance impact, so the improved readability should be worth it.
Still far from ideal, but it's a bit tricky due to relying on cdata structs. May be improved further in the future...
=> Adapt the GND decoder to employ a BinaryReader

Core/FileFormats/BinaryReader.lua, Tests/FileFormats/BinaryReader.spec.lua
It's way more useful to get detailed feedback right away,.
=> Improve the BinaryReader EOF error message

README.md
The problem has solved itself, apparently. I'm not complaining.
=> Remove an outdated note regarding macOS rendering issues

Core/FileFormats/RagnarokGR2.lua
=> Resolve some minor inconsistencies in the GR2 decoder

Core/FileFormats/RagnarokSPR.lua
Just paying down some tech debt. Also, unblocks #177.
=> Modify the SPR decoder to utilize a BinaryReader

Core/FileFormats/RagnarokACT.lua
It's getting a bit crowded in there...
=> Extract sprite layer decoding to a separate function

Core/NativeClient/C_Camera.lua, Core/NativeClient/NativeClient.lua, Core/NativeClient/Renderer.lua, Tests/NativeClient/C_Camera.spec.lua, Tests/NativeClient/NativeClient.spec.lua
This is only for debugging purposes, so it needn't be particularly elaborate.
=> Allow moving the camera target via SHIFT + arrow keys

Tools/extract-from-grf.lua
No bulk extraction since it isn't needed at this time.
=> Create a script to extract files from GRF archives

README.md
I was just looking for an excuse to try this new GitHub feature...
=> Add markdown alerts and more info to the README

Tests/Fixtures/hello.js
=> Get rid of a leftover file from the AssetServer tests

Core/NativeClient/NativeClient.lua, start-client.lua
Probably not the best approach, will revisit and improve as needed.
=> Add a simple stress test via optional CLI args

Tests/DB/validate-map-database.lua, Tests/smoke-test.lua
Forgot about this. Not sure how much it helps, but it's free anyway.
=> Add a smoke test that validates the map database

Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/BasicTriangleDrawingPipeline.lua, Core/NativeClient/WebGPU/Buffer.lua, Core/NativeClient/WebGPU/GPU.lua, Core/NativeClient/WebGPU/Texture.lua
This is much nicer overall (similar to how WebGPU is used from JS).
=> Simplify the WebGPU setup code with FFI initializers

.gitignore, Tools/analyze-act-files.lua, Tools/analyze-gat-files.lua, Tools/analyze-gnd-files.lua, Tools/analyze-rsw-files.lua, Tools/analyze-spr-files.lua
There's been some inconsistencies here. Let's get rid of them real quick.
=> Streamline the directory used for extracted GRF assets

README.md
=> Remove some redundant overflowing text in the README

Core/FileFormats/RagnarokIMF.lua, Tools/imf-to-json.lua
Adding for completion's sake only, doubt this will be useful at all TBH.
---
Resolves #126.
=> Add a FFI-based decoder for IMF files

.github/workflows/static-analysis.yml, validate-shaders.sh
This doesn't solve the problem of "no GPU testing in the CI runner", but it's better than nothing.
=> Add automated validation for the WGSL shaders

validate-shaders.sh
=> Improve the output of the shader validation script

Tools/analyze-water-textures.lua
It's extremely unlikely that this will change. But I'd rather not be surprised.
=> Add some missing assertions to the water analysis script

Core/FileFormats/RSW/AnimatedWaterPlane.lua, Core/FileFormats/RagnarokGND.lua, Core/NativeClient/DebugDraw/Box.lua, Core/NativeClient/DebugDraw/Cone.lua, Core/NativeClient/DebugDraw/Cylinder.lua, Core/NativeClient/DebugDraw/Plane.lua, Core/NativeClient/DebugDraw/Pyramid.lua, Core/NativeClient/DebugDraw/Sphere.lua, Core/NativeClient/DebugDraw/WorldAxis.lua, Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/Mesh.lua, Tests/NativeClient/Renderer.spec.lua, Tests/NativeClient/WebGPU/Mesh.spec.lua, Tests/unit-test.lua
Very bare-bones and with a few parts hacked in (say hello to ~~my little friend~~ `rawget`). More improvements to come.
=> Streamline the handling of mesh geometry to enable future extension

Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/BasicTriangleDrawingPipeline.lua, Core/NativeClient/WebGPU/Buffer.lua, Core/NativeClient/WebGPU/WidgetDrawingPipeline.lua
These are just the default values and they aren't even relevant here, so let's cut down on the extreme verbosity (at least a little bit).
=> Remove some redundant WebGPU default settings

Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/UserInterfaceMaterial.lua, Tests/NativeClient/WebGPU/UserInterfaceMaterial.spec.lua, Tests/unit-test.lua
What material is the user interface made of? Not sure, but hopefully it's tasty...
If the pipeline configuration and bind group management is to be handled by materials, then widgets will need their own material as well since they're dynamically generating GPU resources and complicating the rendering code.
=> Introduce a new material for RML UI widgets

Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/BasicTriangleDrawingPipeline.lua, Core/NativeClient/WebGPU/GroundMeshMaterial.lua, Core/NativeClient/WebGPU/UniformBuffer.lua, Core/NativeClient/WebGPU/UnlitMeshMaterial.lua, Core/NativeClient/WebGPU/UserInterfaceMaterial.lua, Core/NativeClient/WebGPU/WaterSurfaceMaterial.lua, Core/NativeClient/WebGPU/WidgetDrawingPipeline.lua
Tackling the bind groups will be much more risky, so better get this merged in first.
=> Simplify the setup process for rendering pipelines and camera/viewport uniforms via materials

Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/BasicTriangleDrawingPipeline.lua, Core/NativeClient/WebGPU/Texture.lua, Core/NativeClient/WebGPU/UniformBuffer.lua, Core/NativeClient/WebGPU/VirtualGPU.lua, Core/NativeClient/WebGPU/WidgetDrawingPipeline.lua, Tests/NativeClient/Renderer.spec.lua
Slightly awkward still to have textures create their own bind groups, but it's a step in the right direction (focus on materials instead).
=> Streamline the setup of texture (material) bind groups and bind group layouts

Core/NativeClient/Shaders/BasicTriangleShader.wgsl, Core/NativeClient/Shaders/UserInterfaceShader.wgsl
Also removed the unused `deg2rad` utility function since it wasn't needed.
=> Clean up the WGSL shader code (by reformatting and reordering)

Core/FileFormats/RSW/AnimatedWaterPlane.lua, Core/FileFormats/RagnarokMap.lua, Core/NativeClient/WebGPU/Materials/GroundMeshMaterial.lua, Core/NativeClient/WebGPU/Materials/UnlitMeshMaterial.lua, Core/NativeClient/WebGPU/Materials/UserInterfaceMaterial.lua, Core/NativeClient/WebGPU/Materials/WaterSurfaceMaterial.lua, Tests/FileFormats/RSW/AnimatedWaterPlane.spec.lua
=> Implement using special material properties for rendering lava surfaces

Core/NativeClient/Interface/PerformanceMetricsOverlay.lua, Core/NativeClient/NativeClient.lua, Core/NativeClient/Renderer.lua, Tests/NativeClient/Interface/PerformanceMetricsOverlay.spec.lua, Tests/unit-test.lua
=> Implement a method for computing and displaying select rendering performance metrics

Core/FileFormats/RagnarokGND.lua, Core/FileFormats/RagnarokMap.lua, Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/Materials/GroundMeshMaterial.lua, Core/NativeClient/WebGPU/Pipelines/GroundMeshDrawingPipeline.lua, Core/NativeClient/WebGPU/Shaders/BasicTriangleShader.wgsl, Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl, Core/NativeClient/WebGPU/Shaders/UserInterfaceShader.wgsl, Core/NativeClient/WebGPU/Shaders/WaterSurfaceShader.wgsl, Core/NativeClient/WebGPU/UniformBuffer.lua, Tests/FileFormats/RagnarokMap.spec.lua, Tests/NativeClient/Renderer.spec.lua, Tests/NativeClient/WebGPU/GroundMeshMaterial.spec.lua
=> Implement ambient lighting for the ground mesh material

Core/FileFormats/RSW/AnimatedWaterPlane.lua, Core/FileFormats/RagnarokGND.lua, Core/NativeClient/DebugDraw/Box.lua, Core/NativeClient/DebugDraw/Cone.lua, Core/NativeClient/DebugDraw/Cylinder.lua, Core/NativeClient/DebugDraw/Plane.lua, Core/NativeClient/DebugDraw/Pyramid.lua, Core/NativeClient/DebugDraw/Sphere.lua, Core/NativeClient/DebugDraw/WorldAxis.lua, Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/GPU.lua, Core/NativeClient/WebGPU/Mesh.lua, Core/NativeClient/WebGPU/Pipelines/BasicTriangleDrawingPipeline.lua, Core/NativeClient/WebGPU/Pipelines/GroundMeshDrawingPipeline.lua, Core/NativeClient/WebGPU/Pipelines/WaterPlaneDrawingPipeline.lua, Tests/FileFormats/RagnarokGND.spec.lua, Tests/NativeClient/Renderer.spec.lua, Tests/NativeClient/WebGPU/Mesh.spec.lua
Normals aren't actually used yet, but merging this in without the directional light support so that wave animations can be fixed.
=> Enable support for normal buffers in all relevant rendering pipelines

Core/FileFormats/RSW/AnimatedWaterPlane.lua, Core/NativeClient/WebGPU/Shaders/WaterSurfaceShader.wgsl
=> Correct the broken rendition of wave animations

Core/FileFormats/RSW/AnimatedWaterPlane.lua, Core/FileFormats/RagnarokRSW.lua, Tests/Tools/FileAnalyzer.spec.lua, Tools/FileAnalyzer.lua, Tools/analyze-water-types.lua
=> Add support for analyzing water plane properties to the data mining toolkit

Core/FileFormats/RagnarokGND.lua, Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl, Tests/FileFormats/RagnarokGND.spec.lua, Tests/Tools/RagnarokTools.spec.lua, Tools/RagnarokTools.lua
It's unclear whether this is truly accurate, but potential improvements can always be added later.
---
Resolves #213.
=> Implement generating and rendering GND lightmap textures

Core/FileFormats/RagnarokMap.lua, Core/NativeClient/C_Resources.lua, Core/NativeClient/NativeClient.lua, Core/NativeClient/Renderer.lua, Core/NativeClient/WebGPU/GPU.lua, Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl, Core/NativeClient/WebGPU/UniformBuffer.lua, Tests/NativeClient/C_Resources.spec.lua, Tests/NativeClient/NativeClient.spec.lua, Tests/NativeClient/Renderer.spec.lua, Tests/unit-test.lua
Some parts are hacky since the resource management isn't yet fleshed-out, and no idea how accurate it is (need references).
---
Resolves #132.
=> Implement linear vertex fog for RSW-based scenes

Core/NativeClient/WebGPU/GPU.lua, Core/NativeClient/WebGPU/Pipelines/WidgetDrawingPipeline.lua, Core/NativeClient/WebGPU/UniformBuffer.lua
=> Make sure the selected dynamic uniform buffer alignment works on NVIDIA devices

Core/NativeClient/WebGPU/Shaders/WaterSurfaceShader.wgsl
This is clearly an oversight; only sprites and UI widgets should be exempt.
=> Enable vertex fogging for water surfaces

Tests/Tools/FileAnalyzer.spec.lua, Tools/FileAnalyzer.lua
This helps determine which types are actually used in the game.
=> Add support for RSM animation types to the FileAnalyzer

Core/Platforms/Win32.cpp, Core/Platforms/Win32/GamePad.cpp, build.bat
No real use for them right now, but it's barely an inconvenience.
=> Enable basic GamePad controls on Windows (via XInput)

Core/Platforms/Win32.cpp, Core/Platforms/Win32/DebugDraw.cpp
Will have to revisit this once the frame rate isn't single-digits to see how responsive the UI feels.
=> Fix repaint-related flickering and related issues on WM_ACTIVATEAPP (and while resizing)

Core/Numbers.hpp, Core/Platforms/Win32.cpp, Core/Platforms/Win32.hpp, Core/Platforms/Win32/DebugDraw.cpp, Core/Platforms/Win32/Time.cpp, Core/Strings.hpp, build.bat
This fixes a number of issues and enables fancier visualizations (history/graphs etc.).
Still fairly primitive and slow, but it's enough to guide future changes and optimizations.
=> Overhaul the graphical GDI performance metrics display

Core/Platforms/Win32.cpp, Core/RagLite2.hpp, Core/Strings.hpp, build.bat
Not the ultimate solution, but it's a starting point.
=> Append a commit hash suffix to the main window title

Core/Platforms/Win32/DebugDraw.cpp
Without these, the program crashes when resizing the window while outside of fullscreen mode.
Also fixes clipping-related errors and oversights in the line drawing algorithm and utility code.
=> Enable clipping for GDI back buffer writes to prevent OOB access
