Core/World/C_ServerHealth.lua
Tests/WorldServer/C_ServerHealth.spec.lua

See commit messages - this "fixes" the standard deviation being computed as "nan" (by failing loudly) as it's likely unintended.

Fix server health metrics for single-data point sets

---

Core/WorldServer.lua

As a follow-up to #11, moving from a sleep-based to a timer-based loop seems to almost double the throughput.
Since the event loop sleeps internally anyway, this should be functionally identical and not cost (significantly) more CPU, so there's no reason to sleep manually here.
Unfortunately, testing timers is always icky, but degradation should be obvious if the target frame rate isn't reached (while idle).

Improve the performance of the update loop

---

Tests/smoke-test.lua
Tests/unit-test.lua
main.lua

By default, the system LUA_PATH is used to determine the lookup path. While this works with a default configuration (as evidenced by CI runs), it's not guaranteed to work. Since the general assumption (for now) is to use standard require with relative paths from the project root, it would be prudent to make sure the lookups always succeed.

Set package.path explicity to avoid OS-dependent lookups

---

Core/FileFormats/RagnarokGRF.lua
Tests/FileFormats/RagnarokGRF.spec.lua

If the name has been normalized before, as is the case when using the file entry to extract all files from a given GRF archive, the lookup would fail because the UTF8-encoded name is again multibyte-decoded, which yields incorrect results.
Instead of doing fancy checks, let's keep it simple and assume that this is the only situation to deal with. Checking both entries while performing the lookup is the most straightforward solution.

Fix GRF extraction for UTF8-encoded file paths

---

Core/AssetServer.lua
Tests/AssetServer/AssetServer.spec.lua

The browser doesn't know what to do with them if the server doesn't set the appropriate content type header.

Support additional media types in the asset server

---

Core/WebClient/tsconfig.json

No idea why it sometimes tries to do this, but it obviously won't work.

Prevent TypeScript from compiling the output bundle

---

Core/WebClient.lua

It seems that the fullscreen mode on OSX is a bit odd: The runtime fails to show the window when no size has been specified, and then when it tries to toggle fullscreen mode it can't scale up the window (perhaps its size is initialised with zero?).
That aside, it's probably a good idea to set a default size anyway.

Set a default WebView window size so that fullscreen mode works on Mac OS

---

Core/WebClient/package.json

Starting the WebClient as a standalone app (without the Lua runtime) doesn't make any sense, and this is easier to type than "npm run dev".

Rename the npm dev script so that it's easier to use

---

Core/AssetServer.lua
Tests/AssetServer/serves-grf-index.lua
Tests/smoke-test.lua

This allows the WebView to easily determine whether it's compatible with the GRF contents, request files, and aids debugging in general. Sending 10MB of JSON data around isn't really efficient, but it's not going over the network if using localhost, so whatever.

Add a new route to the asset server that serves the GRF file list as JSON

---

Core/WebClient/index.html

That's just immersion-breaking and not needed, anyway.

Disable the default browser context menu on right click

---

Tools/dump-gnd-lightmap.lua

This is the same format that GNDedit used, ported from the existing JavaScript implementation (optimized via FFI and cleaned up).
The format is NOT suitable for rendering and it's also wasteful, doesn't include wall surfaces, etc. It's mostly for debugging/tools.

Add a script to dump human-readable GND lightmaps

---

Core/NativeClient/NativeClient.lua
Tests/NativeClient/NativeClient.spec.lua

When pressing LEFT and then RIGHT, it shouldn't count as double click.

Fix accidental camera resets via left-right click sequences

---

Core/NativeClient/NativeClient.lua
Tests/NativeClient/NativeClient.spec.lua

When releasing the mouse button and immediately clicking, the view is always reset - even if the button was pressed a long time ago (or, as in the test case, never). This is unintuitive, as the unspoken convention used by the client currently is that a keypress should be triggered on "press" and never "release".
Ideally, that'd be configurable but it's not that important right now.

Fix a glitch in the double-click camera reset logic

---

Core/FileFormats/RagnarokGRF.lua

Still very slow, on the order of 750ms. About 550ms is just the inefficient file path normalization. Should improve that later.

Speed up the initial loading time due to GRF file table decoding

---

Core/FileFormats/RagnarokGRF.lua
Core/RuntimeExtensions/cstring.lua
Tests/FileFormats/RagnarokGRF.spec.lua

From 800ms to 400ms on my machine. Still not ideal, but even moving the code to C++ with iconv and preallocated buffers didn't help much, so might as well keep using the FFI for now. The iconv stuff should be moved to the runtime regardless (later).
Edit: This is on Windows. The iconv code needs a rework, but it's not that important right now. as I don't use WSL as often.

Reduce the file table decoding time via further FFI calls

---

Core/NativeClient/WebGPU/GPU.lua

It's implicitly assumed that we'll use a proper GPU, so fail if we can't.

Ensure high-powered WebGPU adapters are always requested

---

Core/NativeClient/Renderer.lua

The upload actually happens on the GPU timeline, so this is pointless.

Remove misleading profiling output for geometry uploads

---

Core/NativeClient/WebGPU/Texture.lua

This doesn't make any difference right now, but if invalid UVs are passed then debugging repeating samples can be a pain.

Ensure that texture coordinates are always clamped

---

Core/FileFormats/BinaryReader.lua
Tests/FileFormats/BinaryReader.spec.lua
Tests/unit-test.lua

Mostly safe, as long as `GetUnsafePointer` isn't used... I don't think it gets much more usable when the FFI is involved.
I've already ported the GND decoder (separate PR). It seems there's no measurable performance drop, so that's a win.

Implement a BinaryReader class to simplify the FFI-based decoders

---

Tools/RagnarokTools.lua

It will come in handy later, when it's time to export other textures.

Move an inlined utility function to the module level

---

.github/workflows/ci-linux.yml
.github/workflows/ci-mac.yml
.github/workflows/ci-windows.yml
.github/workflows/typescript-build.yml

They use an outdated Node version, which is force-updated by GitHub.

Update all GitHub Actions workflows to use checkout v3

---

Core/FileFormats/RagnarokGRF.lua
Tests/FileFormats/RagnarokGRF.spec.lua
Tools/analyze-gnd-files.lua
Tools/analyze-spr-files.lua

The original code was always a hack, and also seems to have had a bug that leads to SEGFAULTing on Linux?
Either way, with iconv in the runtime there's no need for it anymore. Good riddance!

Replace platform-specific multibyte decoding hacks in the GRF decoder with iconv.convert

---

Core/FileFormats/RagnarokGRF.lua
Tests/FileFormats/RagnarokGRF.spec.lua

Maybe it's OCD, but this just seems a bit too awkward for my taste.

Rename the aligned size field of GRF file entries

---

Tools/FileAnalyzer.lua

When mutating the same object repeatedly, headaches may ensure.

Prevent a potential source of errors in the future

---

Core/FileFormats/RagnarokGR2.lua
Tests/FileFormats/RagnarokGR2.spec.lua
Tests/unit-test.lua
Tools/gr2-to-json.lua

Doesn't process the data segments, just the outer structures (as described by OpenGR2).
It's probably also wrong in some aspects, but there's no telling anyway until further analysis has been performed.

Add a new FFI-based decoder for GR2 files

---

Tools/dump-gr2-segments.lua

This might come in handy later, as it isolates the compressed data.

Create a script to dump raw GR2 segment bytes

---

Core/FileFormats/RSW/QuadTreeRange.lua

Since the Y axis is inverted, the highest point is actually the "min".

Fix some misleading QuadTreeRange property names

---

Tools/dump-grf-file-list.lua

Optional because it's freaking slow... and not always useful.

Implement optionally tagging GRF file list dumps

---

Core/FileFormats/RagnarokGND.lua
Core/FileFormats/RagnarokSPR.lua

Should've been there from the start.

Add a missing EOF sanity check to the SPR and GND decoders

---

Core/VectorMath/Vector3D.lua
Tests/VectorMath/Vector3D.spec.lua

Trivial but missing primitive that will come in handy shortly.

Implement addition for Vector3D metatypes

---

Tests/FileFormats/RagnarokGR2.spec.lua

Seems like an oversight. No point in keeping this around.

Remove an empty setup function from the GR2 tests

---

Tests/unit-test.lua

Convenient for local testing. Should not affect CI runs at all.

Allow running selected unit tests only

---

Core/NativeClient/Renderer.lua

It's a `WGPUBool`, i.e., `uint32`, so zero means false (but 0 evaluates to true in Lua).

Fix an incorrect assertion in the WebGPU renderer

---

Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/BasicTriangleDrawingPipeline.lua
Core/NativeClient/WebGPU/Surface.lua

The original prototype leaned heavily on the swap chain, which is no longer a thing in the latest WebGPU API.

Restructure the WebGPU surface handling logic

---

Core/RuntimeExtensions/C_Runtime.lua
Tests/RuntimeExtensions/C_Runtime.spec.lua
Tests/unit-test.lua

Not sure about this, but the idea is to detect test runs in GPU code (to drop WebGPU API calls that won't work in the CI). It's a first step towards adding more testable instrumentation in the renderer.
If this turns out to be useful, it could be moved into the runtime itself, but for the time being it's just an experiment that doesn't warrant a dedicated runtime upgrade.

Extend the runtime to allow detecting test runs

---

Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/BasicTriangleDrawingPipeline.lua
Core/NativeClient/WebGPU/CommandEncoder.lua
Core/NativeClient/WebGPU/Device.lua
Core/NativeClient/WebGPU/Queue.lua
Core/NativeClient/WebGPU/RenderPassEncoder.lua
Core/NativeClient/WebGPU/Texture.lua

This might seem a bit questionable (and perhaps I'll end up reverting it), but ideally all external API calls would be hidden so that they can be unit tested more freely, where it makes sense.
The facade is a 1:1 mapping to the WebGPU API that currently exposes about 180 functions, a tiny subset of which are actually used by the renderer. That is to say, the maintenance overhead should be negligible as I don't plan to use most of the features.
There may be an opportunity to add event tracing/logging here, too.

Hide all WebGPU API calls behind facade classes

---

Core/FileFormats/BinaryReader.lua
Tests/FileFormats/BinaryReader.spec.lua

This prevents errors when debugging via lldebug, as it may crash if the metatable doesn't have a length property. Besides that, it's also a convenient shorthand with low maintenance overhead.
Note: `GetBufferSize` is a more readable alias, mostly added for consistency.

Add a __len metamethod to the BinaryReader class

---

.github/workflows/ci-mac.yml
README.md

Back in my day, it was called "Mac OS X". Apparently, that has changed.

Consistently apply the official spelling of macOS

---

Core/RuntimeExtensions/etrace.lua
Tests/RuntimeExtensions/etrace.spec.lua
Tests/unit-test.lua

Not sure how many features are needed. For now, all that matters is that the WebGPU calls can be traced (for testing purposes).

Add a new etrace module (experimental event tracing library) as a runtime extension

---

Core/NativeClient/Renderer.lua

Huh, this doesn't make any sense at all... The scenewide uniform data needs to be updated once per frame, not once per mesh. Perhaps this was supposed to be per-material or even per-mesh data, but I think it's just a copy/paste error.
Caught this thanks to tracing API calls, so `etrace` already paid off... These writes are wasteful and can safely be removed.

Eliminate some redundant WebGPU buffer writes

---

Core/NativeClient/NativeClient.lua
Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/Queue.lua
start-client.lua

This mostly just serves as an example, more traces are to follow. Works with any `wgpu` call, though it may potentially be verbose.

Add event tracing for some WebGPU API calls

---

Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/Buffer.lua
Core/NativeClient/WebGPU/GPU.lua

The largest GND file is `schg_dun01`, so using that as a "worst case scenario" seems like a reasonable choice.
* 16-bit indices are insufficient to render meshes with 80k+ vertices, so let's just use 32-bit (even if it's wasteful for other maps)
* The maximum vertex buffer size also needs increasing as the terrain meshes are HUGE - maybe they could be optimized?
This is split off from the other changes to make sure the GND rendering PR won't be as large as it currently is...

Increase the limits of the WebGPU pipeline so that large GND terrain geometry may be rendered

---

Core/NativeClient/WebGPU/Texture.lua

According to the WebGPU spec, this alignment restriction doesn't apply when using writeTexture.

Remove an overly-strict assertion regarding WebGPU texture alignment that fails when trying to use small images

---

Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/Texture.lua
Core/NativeClient/WebGPU/VirtualGPU.lua
Tests/NativeClient/Renderer.spec.lua
Tests/unit-test.lua

Trivial addition, but perhaps more interesting: An experimental "virtual GPU" to allow unit testing in the absence of GPU runners.
I still have to look into running fully-featured tests, at least on Windows, but lacking that at least the WebGPU calls can be traced.

Add a way for the WebGPU renderer to load arbitrary texture images (including a somewhat questionable approach to testing)

---

Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/Buffer.lua
Core/NativeClient/WebGPU/Queue.lua
Core/NativeClient/WebGPU/VirtualGPU.lua
Core/RuntimeExtensions/etrace.lua
Tests/NativeClient/Renderer.spec.lua
Tests/RuntimeExtensions/etrace.spec.lua
Tests/unit-test.lua

They're still quite messy and not sure I like the call interception approach, but for now it'll have to do.
Oh, and I guess `DestroyMeshGeometry` is technically "new" since it wasn't merged into the `main` branch yet...

Add unit tests for the WebGPU renderer's geometry transferral APIs

---

Core/NativeClient/Renderer.lua
Core/NativeClient/Shaders/BasicTriangleShader.wgsl
Tests/NativeClient/Renderer.spec.lua

Resolves #214. It's not at all optimized, can probably get a lot better by just moving it to the runtime (C++). Maybe later?

Implement a preprocessing step for diffuse textures that discards the magenta background pixels

---

Core/FileFormats/RagnarokSPR.lua
Tests/FileFormats/RagnarokSPR.spec.lua

The background pixels need to be discarded, but none of the others.

Fix transparency values for decoded SPR images

---

Core/FileFormats/RagnarokGRF.lua
Tests/FileFormats/RagnarokGRF.spec.lua

The preallocation happens in the constructor, but that isn't really required in this case since the method doesn't depend on the decoded file table (or other internal data). Multithreading isn't an issue here either, so there's no reason to not share a single conversion buffer. In fact, enabling the use of this as a static method makes it more convenient for other decoders to use the conversion code... although it's questionable that they should need to in the first place.

Allow the GRF decoder's DecodeFileName method to be used statically

---

Core/FileFormats/RagnarokGRF.lua
Tests/FileFormats/RagnarokGRF.spec.lua

Improves the experience slightly when forgetting to call `Open()` first.

Add a sanity check for detecting uninitialized GRF file handles

---

Core/VectorMath/Vector3D.lua

This format works better when the vector is printed inline.

Modify the __tostring output format for Vector3D objects

---

Core/FileFormats/RagnarokGRF.lua
Tests/FileFormats/RagnarokGRF.spec.lua

The utility here is finding worst case examples more easily.

Add a method to find the largest files by type

---

README.md

There's no "classic" database anymore, just *a* map database,

Fix some database-related info in the README

---

README.md

Without the file extension this won't work as expected.

Fix an oversight in the README's usage instructions

---

Tools/extract-from-grf.lua

I don't think the capability of changing the GRF name and destination folder is worth more than being able to use shell tools to extract arbitrary numbers of files with a single command (to me, anyway).

Rework the GRF extraction script to support multiple files

---

autoformat.sh

This prints the time taken to format a given file, among other things. Since some database and test files are quite chunky, it could be useful to see when formatting them takes too much time to be worth it (so that it can be disabled).

Enable verbose output for the autoformat script

---

Core/FileFormats/RagnarokGND.lua
Tests/FileFormats/RagnarokGND.spec.lua

It's a bit slower than the code used in the terrain generation since it computes more stuff that simply isn't needed there, so I haven't reused it (even though that works just fine). May need to optimize later, but for now that doesn't matter as I don't have any performance-critical use cases in mind. The tests are painfully repetitive, so that may need some streamlining as well (deferred).

Add a method to translate GND to world coordinates

---

Core/NativeClient/Renderer.lua

Seems a bit confusing to say that geometry is being uploaded if it's actually skipped.

Improve the debug messages that are displayed on mesh upload

---

Core/NativeClient/Renderer.lua

It hasn't been used in a while, and the renderer shouldn't keep track of pipelines anyway (the code is already far too complicated).

Remove an unused field from the Renderer module

---

Core/NativeClient/Renderer.lua

This uniform data is changing exactly once per frame (in `UpdateScenewideUniformBuffer`), so there's no point in adding redundant API calls to the render pass encoder for every mesh. It's possible the implementation would optimize them away, and there aren't enough meshes being rendered for it to become a problem right now, but such a potential foot gun shouldn't be ignored. The same applies for the UI widgets, of which there is only one right now (but it has the same potential problem).

Avoid repeatedly binding resources that change only once per frame for every mesh and UI widget

---

Core/FileFormats/BinaryReader.lua
Core/FileFormats/RagnarokGRF.lua
Core/FileFormats/RagnarokPAL.lua
Core/FileFormats/RagnarokSPR.lua
Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/GPU.lua
Core/NativeClient/WebGPU/Surface.lua
Core/VectorMath/Matrix3D.lua
Core/VectorMath/Matrix4D.lua
Core/VectorMath/Vector3D.lua
Tests/NativeClient/WebGPU/Texture.spec.lua

Removing the upvalues entirely isn't advisable as global lookups still generate more instructions*, but the use of localized FFI calls should be consistent across the codebase.
(*Based on these benchmarks, which I haven't personally verified: https://gitspartv.github.io/LuaJIT-Benchmarks/)

Streamline the use of localized ffi API references

---

autoformat.sh

Some of the database files are huge, so formatting takes a lot of time and hogs memory.
Since they're rarely changed, can skip them for local development (but never in CI runs).

Add an optional flag to the autoformat script to skip formatting large database files when it isn't needed

---

.github/workflows/ci-windows.yml
Tests/FileFormats/RagnarokACT.spec.lua
Tests/FileFormats/RagnarokGND.spec.lua

This probably explains the issues with test fixtures failing the equality comparison in some of the decoder test cases?

Disable git's autocrlf feature in the Windows CI runner

---

Tests/smoke-test.lua
Tests/unit-test.lua
client.lua
server.lua

Not sure why I added those, require should "just work" from the current working directory by default?

Remove the obsolete package.path adjustments

---

Core/NativeClient/NativeClient.lua
Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/Shaders/BasicTriangleShader.wgsl
Core/NativeClient/WebGPU/Shaders/UserInterfaceShader.wgsl
Core/NativeClient/WebGPU/UniformBuffer.lua

The first frame is set to zero so that animation state updates are effectively a NOOP (to prevent potential animation glitches).
---
First part of a basic animation system, split into multiple PRs since there's again too much scope creep.

Implement delta time updates for the WebGPU renderer

---

Core/NativeClient/Interface/PerformanceMetricsOverlay.lua
Core/NativeClient/NativeClient.lua
Tests/NativeClient/Interface/PerformanceMetricsOverlay.spec.lua

Both are estimates and not expected to be 100% accurate due to various complexities like multithreading/C++ vs Lua etc.
The primary goal is to detect excessive resource usage and other "obvious" outliers, such as huge memory leaks or delays.

Add CPU and memory usage to the performance metrics overlay

---

Core/NativeClient/DebugDraw/Scenes/walls.lua

I made this primarily to debug the normals visualization. Might as well keep it, in case the winding order must change again.

Create a new debug scene for surface normals

---

Core/NativeClient/WebGPU/Mesh.lua
Tests/NativeClient/Renderer.spec.lua

This causes sporadic CI failures because the function call detection is wonky. It's also outdated since each mesh now requires five buffers and not three, so a bit of generalization may be needed here. Still not great, but should at least reliably pass.

Fix a flaky test for the WebGPU renderer

---

Core/FileFormats/RagnarokRSW.lua
Tests/FileFormats/RagnarokRSW.spec.lua

It's not pretty, but it does prevent crashes when loading gl_step...
---
Resolves #343.

Add a workaround for NaN light positions to the RSW decoder

---

Core/FileFormats/RagnarokRSW.lua

This also accounts for the inverted Y axis, but makes it clearer that the sunlight origin is located directly above the map.

Simplify the RSW directional light computation

---

Core/FileFormats/RagnarokGND.lua
Core/FileFormats/RagnarokMap.lua
Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/GPU.lua
Core/NativeClient/WebGPU/Materials/GroundMeshMaterial.lua
Core/NativeClient/WebGPU/Materials/InvisibleBaseMaterial.lua
Core/NativeClient/WebGPU/Mesh.lua
Core/NativeClient/WebGPU/Pipelines/BasicTriangleDrawingPipeline.lua
Core/NativeClient/WebGPU/Pipelines/GroundMeshDrawingPipeline.lua
Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl
Tests/FileFormats/RagnarokGND.spec.lua
Tests/NativeClient/Renderer.spec.lua

Very basic and using some placeholders for the lightmap texture and UVs. Needs adjustments to the sampling method, as well.
---
Resolves #131.

Add support for lightmap textures to the WebGPU renderer

---

Tests/Tools/RagnarokTools.spec.lua
Tools/RagnarokTools.lua

I think this used to be ignored, but now it isn't so the final image will be fully transparent. Tests didn't catch it either, apparently.

Fix the alpha channel for generated GAT images

---

Tests/Tools/RagnarokTools.spec.lua

The tests actually try to assert that the generated PNG bytes are identical, but this isn't the case when running them on M1-based macOS systems. It also doesn't really make sense; only the image contents should be validated and not the on-disk representation.
The fact that this worked at all is likely a happy accident.

Fix the checksum tests for generated GAT images

---

Tools/RagnarokTools.lua

The previous approach to normalization is nonsensical and fails when encountering certain values, including those used by the test fixtures. This manifests differently on the M1 runner (using ARM64), which is why the CI kept failing even after the last few fixes. Not sure if this normalization method is the best choice, as the contrast is quite low in certain maps (e.g., prontera). But at least it shouldn't generate NaN/invalid results.

Rework the GAT heightmap image generation script

---

Core/NativeClient/NativeClient.lua

Yeah, yeah... there's still no actual keybinding system. For now this will have to do.
No idea how to test this, so it's just undefined behavior I guess.

Add a keybind for exiting on ESCAPE key presses

---

Core/NativeClient/WebGPU/Surface.lua

I didn't even notice this until implementing the ESC binding. With that, it's easy to test - press ESC immediately and the surface will become invalid while shutting down. However, the failure reason given will be "nil" instead of the intended message.

Fix the failure reason given when skipping frames due to outdated surfaces

---

Core/NativeClient/NativeClient.lua
client.lua

In order to get accurate profiling results, the render loop needs to be stopped immediately after loading the given scene.

Add a new CLI switch for profiling the startup time

---

Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl
Tests/NativeClient/Renderer.spec.lua

This reduces the loading times, at the cost of having to perform more checks on the GPU. I highly doubt GPU usage will be an issue however, whereas loading times are very painful in general.
The drawback here is that if a single texture was to be reused many times, it would incur a runtime cost for each instance, whereas pre-processing has a startup cost shared between all instances. But I doubt it's relevant here, and there's no mechanism to reuse resources currently, anyway.
---
Before this change:
* Loading `yuno` takes about **2.1 seconds**
* Loading `icecastle` takes about **2.2 seconds**
* Loading `pay_dun00` takes about **1.1 seconds**
* Loading `schg_dun01` takes about **2.4 seconds**
* Loading `prontera` takes about **0.9 seconds**
After this change:
* Loading `yuno` takes about …

Discard transparent background pixels in the fragment shader instead of a separate CPU pre-processing step

---

Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl

This error was concealed by a recent change to wgpu, where it would automatically convert unsigned integers to floats when it deems it "safe" to do so. Previously, it would've given a validation error here because the hardcoded numbers aren't compiled to floats unless explicitly marked as such.
Apparently, this hidden conversion broke the discard logic, leading to black surfaces being discarded in at least one case (c_tower1). This is because the division doesn't have enough precision if using integers. Being explicit fixes the problem.
Edit: I also noticed the shader isn't actually discarding the fragment, which seems like a silly oversight.

Fix an unintended type conversion in the terrain shader

---

Core/FileFormats/RagnarokRSM.lua
Core/FileFormats/RagnarokRSW.lua

The files can't be loaded with their gibberish name as GRF paths are normalized on load. Also, it's just inconsistent right now.

Add normalization steps for RSM names and file paths to the RSM and RSW decoders

---

Core/FileFormats/RagnarokRSM.lua

If these aren't initialized, `__index` may get stuck recursively looking up `nil` values.
The settings aren't used anyway, so might as well assign some defaults to avoid more `rawget` shenanigans.

Fix lookups for optional RSM2 animation parameters

---

Core/FileFormats/RagnarokRSM.lua
Tools/rsm-to-json.lua

This doesn't currently work due to a bug in the JSON encoder; it will throw when encountering FFI metatypes and other unexpected value types. After the next runtime update, this problem should no longer exist.

Add a utility script to dump RSM files as JSON

---

Core/NativeClient/DebugDraw/Color.lua
Core/NativeClient/Renderer.lua

The brighter color was useful for debugging, but certain maps are designed to incorporate the background color so it looks wrong.

Change the default scene clear color to BLACK

---

Tools/analyze-water-types.lua

The file list should contain both RSW and GND maps, but unpacking tables with duplicate indices doesn't work the same way in Lua as it does in JavaScript. The end result is that only the GND maps are collected as the previously unpacked keys are overwritten.

 Fix an oversight in the water types analysis script

---

Core/NativeClient/Renderer.lua
Core/NativeClient/WebGPU/Pipelines/GroundMeshDrawingPipeline.lua
Core/NativeClient/WebGPU/Pipelines/WaterPlaneDrawingPipeline.lua
Core/NativeClient/WebGPU/RenderTargets/ScreenshotCaptureTexture.lua
Core/NativeClient/WebGPU/Shaders/BasicTriangleShader.wgsl
Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl
Core/NativeClient/WebGPU/Shaders/UserInterfaceShader.wgsl
Core/NativeClient/WebGPU/Shaders/WaterSurfaceShader.wgsl
Core/NativeClient/WebGPU/Surface.lua
Core/NativeClient/WebGPU/Texture.lua

After some investigation, it's become clear that the reference client seems to incorrectly mix sRGB and linear-space colors. While this is a bit of a guess, it would explain why the contrast correction was needed in the first place; it makes up for the underexposure introduced by the lack of gamma-decompression steps after loading sRGB-encoded textures. Indeed, screen blending is used for this exact purpose in digital photo editing (apparently). At least that's the best explanation I could come up with so far.
In order to reproduce the resulting outputs, neither sRGB nor linearized colors can be used. The "in-between"  method used so far, however, trips up the alpha blend stage while the underlying texture view is in sRGB format: WebGPU automatically converts the fragment colors - first …

Fix alpha compositing for translucent water surfaces

---

Core/FileFormats/RagnarokGND.lua
Tests/FileFormats/RagnarokGND.spec.lua
Tests/Tools/RagnarokTools.spec.lua

It seems that the "posterization effect" is a due to the use of 16-bit colors. Ergo, the lightmap alpha channel also needs to be posterized since there's no way to store more than 4 bits for each channel.

Enable posterization of the lightmap alpha channel

---

Core/FileFormats/RagnarokMap.lua
Core/NativeClient/WebGPU/Texture.lua
Tests/FileFormats/RagnarokMap.spec.lua
Tests/NativeClient/WebGPU/Texture.spec.lua

Colors being limited to 16 bits per pixel means that all textures need to be posterized, not just the lightmaps. The resulting color banding softens certain highlights, e.g. on xmas_fild01 - removing it causes some spots to look "off" as they're way too bright.
This code isn't optimized at all since the posterization step doesn't seem to take significant time anyway. Can move it into the runtime's image processing API if that ever becomes necessary. For now, there's no use in doing this, at least for GND textures.

Implement color banding for diffuse texture images

---

Core/NativeClient/WebGPU/Shaders/TerrainGeometryShader.wgsl

It's clear that the alpha channel should not be affecting the lighting stage as that's taking place prior to texture blending.

Fix some errors in the lightmap blending stage for terrain surfaces

---

Tests/NativeClient/Interface/PerformanceMetricsOverlay.spec.lua

This section was accidentally defined as a subsection of `GetFormattedMetricsString`. Both should be at the same nesting level.

Fix a subsection nesting issue in the UI test suite

---

Core/Assertions.hpp
Core/Intrinsics.hpp

These aren't needed when using a debugger, and a popup alert with exit would be more useful for development/CI workflows.

Remove Windows API calls from debug assertions

---

Core/Platforms/Win32.cpp
Core/Platforms/Win32/Time.cpp

This isn't going to change, so no need to call it every frame.

Move GetSystemInfo calls out of the render loop

---

.github/workflows/ci-windows.yml
README.md

It's an experiment - not really useful in the current form.
---

Upload Win32 executables as temporary build artifacts

---

Core/Platforms/Win32.cpp

If responsiveness is an issue, this isn't the way to improve it.

Remove GDI debug overlay updates from WM_KEYUP

---

Core/Platforms/Win32.cpp

XY plot spikes, not a big deal. But the area chart is completely broken when the sleep time far surpasses the frame time:
I don't know that the UX of handling minimized windows is ideal yet, but that's a problem best saved for later.

Prevent frame time graphs from breaking after the window was minimized

---

Core/Numbers.hpp
Core/Platforms/Win32.cpp
Core/Platforms/Win32/DebugDraw.cpp
Core/Platforms/Win32/DebugDraw.hpp

This hopefully makes the dependency chain more obvious. That is:
* WinMain retrieves a persistent display device context (cached via CS_OWNDC)
* From this an in-memory "offscreen" device (back buffer) can be created
* The surface stores all information needed to do blitting later
* DebugDraw rendering APIs write into the opaque GDI context every frame
* Rendering then means "resize/create backbuffer + draw into it + blit to surface"
The simplified buffer handling also uncovered a memory leak; it turns out the in-memory DC was never destroyed (ouch).

Streamline the GDI buffer management code

---

Core/Numbers.hpp
Core/Platforms/Win32.cpp
Core/Platforms/Win32/DebugDraw.cpp

How to speed up Windows code: Remove as much of it as possible.
I may or may not have no clue how to use GDI properly? Alas.
Writing into the buffer directly also makes it easier to debug.
---
Before:
After:

 Replace slow GDI draw calls with direct back buffer writes
